import'dotenv/config';import express from'express';import cors from'cors';import helmet from'helmet';import path from'node:path';import{fileURLToPath}from'node:url';import crypto from'node:crypto';import{clerkMiddleware}from'@clerk/express';import{migrate,q,tx}from'./db.js';import{protect}from'./auth.js';import*as provider from'./provider.js';
const app=express(),port=Number(process.env.PORT||3000),origins=(process.env.APP_ORIGIN||'http://localhost:5173').split(',').map(x=>x.trim()).filter(Boolean);app.disable('x-powered-by');app.set('trust proxy',1);app.use(helmet({contentSecurityPolicy:false}));app.use(cors({origin:origins.length===1?origins[0]:origins,credentials:true}));app.use(express.json({limit:'128kb'}));const clerk=clerkMiddleware();app.use((req,res,next)=>{if(req.path.startsWith('/api/')&&req.path!=='/api/health')return clerk(req,res,next);next()});
app.get('/api/health',async(_req,res)=>{try{await q('SELECT 1');res.json({ok:true,service:'bashpay'})}catch{res.status(503).json({ok:false})}});
app.get('/api/provider-status',protect,async(_req,res)=>res.json(provider.providerStatus()));
app.get('/api/dashboard',protect,async(req,res)=>{const u=req.ctx!.id;const[assets,wallets,transactions,transfers,spaces,requests,alerts,rates]=await Promise.all([q(`SELECT code,name,type,decimals,active FROM bashpay_assets WHERE active ORDER BY id`),q(`SELECT w.id,a.code asset_code,a.name asset_name,w.balance,w.available_balance FROM bashpay_wallets w JOIN bashpay_assets a ON a.id=w.asset_id WHERE w.user_id=$1 ORDER BY w.id`,[u]),q(`SELECT * FROM bashpay_transactions WHERE user_id=$1 ORDER BY created_at DESC LIMIT 50`,[u]),q(`SELECT * FROM bashpay_transfers WHERE user_id=$1 ORDER BY created_at DESC LIMIT 50`,[u]),q(`SELECT * FROM bashpay_spaces WHERE user_id=$1 ORDER BY created_at DESC`,[u]),q(`SELECT * FROM bashpay_requests WHERE user_id=$1 ORDER BY created_at DESC`,[u]),q(`SELECT * FROM bashpay_alerts WHERE user_id=$1 ORDER BY created_at DESC`,[u]),q(`SELECT * FROM bashpay_exchange_rates ORDER BY updated_at DESC`)]);res.json({user:(await q(`SELECT id,email,first_name,last_name,clerk_user_id FROM bashpay_users WHERE id=$1`,[u]))[0],assets,wallets,transactions,transfers,spaces,requests,alerts,exchangeRates:rates,provider:provider.providerStatus()})});
app.post('/api/spaces',protect,async(req,res)=>{const name=String(req.body?.name||'').trim();if(!name)return res.status(400).json({error:'Name required'});res.json((await q(`INSERT INTO bashpay_spaces(user_id,name,description) VALUES($1,$2,$3) RETURNING *`,[req.ctx!.id,name,String(req.body?.description||'')]))[0])});
app.post('/api/requests',protect,async(req,res)=>{const amount=Number(req.body?.amount),currency=String(req.body?.currency||'').toUpperCase();if(!Number.isFinite(amount)||amount<=0||!currency)return res.status(400).json({error:'Invalid request'});res.json((await q(`INSERT INTO bashpay_requests(user_id,amount,currency,description) VALUES($1,$2,$3,$4) RETURNING *`,[req.ctx!.id,amount,currency,String(req.body?.description||'')]))[0])});
app.post('/api/payments/checkout',protect,async(req,res)=>{if(!provider.providerStatus().configured)return res.status(503).json({error:'Flutterwave is not configured'});const amount=Number(req.body?.amount),currency=String(req.body?.currency||'NGN').toUpperCase();if(!Number.isFinite(amount)||amount<=0)return res.status(400).json({error:'Invalid amount'});const txRef=`BASH-${Date.now()}-${Math.random().toString(16).slice(2)}`;await q(`INSERT INTO bashpay_payment_intents(user_id,tx_ref,amount,currency) VALUES($1,$2,$3,$4)`,[req.ctx!.id,txRef,amount,currency]);const p=await provider.checkout({tx_ref:txRef,amount,currency,email:req.ctx!.email,redirect_url:`${process.env.APP_ORIGIN||''}/?funding=return`});res.json({link:p.link,txRef})});
app.get('/api/provider/banks/:country',protect,async(req,res)=>{try{res.json({banks:await provider.banks(String(req.params.country||'NG'))})}catch(e){res.status(502).json({error:e instanceof Error?e.message:'Provider unavailable'})}});
app.post('/api/provider/resolve-account',protect,async(req,res)=>{try{res.json(await provider.resolve(String(req.body?.bankCode),String(req.body?.accountNumber)))}catch(e){res.status(502).json({error:e instanceof Error?e.message:'Provider unavailable'})}});
app.post('/api/transfer-preview',protect,async(req,res)=>{const amount=Number(req.body?.amount),currency=String(req.body?.currency||'').toUpperCase(),internal=String(req.body?.destinationType||'INTERNAL')==='INTERNAL',fee=internal?0:amount*.001;res.json({amount,currency,recipient:String(req.body?.recipient||''),fee,debitedTotal:amount+fee,internalSkyLink:internal,executed:false})});
app.post('/api/transfers',protect,async(req,res)=>{const amount=Number(req.body?.amount),currency=String(req.body?.currency||'').toUpperCase(),dest=String(req.body?.destinationType||'INTERNAL'),idem=String(req.get('Idempotency-Key')||'');if(!Number.isFinite(amount)||amount<=0||!idem)return res.status(400).json({error:'Valid amount and idempotency key required'});const old=await q(`SELECT reference,status,fee,amount FROM bashpay_transfers WHERE user_id=$1 AND idempotency_key=$2 LIMIT 1`,[req.ctx!.id,idem]);if(old[0])return res.json({...old[0],executed:false});const fee=dest==='EXTERNAL'?amount*.001:0,total=amount+fee;if(dest==='EXTERNAL'&&(!provider.providerStatus().configured||process.env.LIVE_PAYMENTS_ENABLED!=='true'))return res.status(503).json({error:'External payouts are not enabled'});const w=await q<{id:string;available_balance:string}>(`SELECT w.id,w.available_balance FROM bashpay_wallets w JOIN bashpay_assets a ON a.id=w.asset_id WHERE w.user_id=$1 AND a.code=$2 FOR UPDATE`,[req.ctx!.id,currency]);if(!w[0]||Number(w[0].available_balance)<total)return res.status(400).json({error:'Insufficient available balance'});const reference=`BASH-TX-${Date.now()}-${Math.random().toString(16).slice(2)}`;const out=await tx(async c=>{await c.query(`UPDATE bashpay_wallets SET balance=balance-$1,available_balance=available_balance-$1,updated_at=NOW() WHERE id=$2`,[total,w[0].id]);const r=await c.query(`INSERT INTO bashpay_transfers(user_id,recipient,amount,currency,fee,destination_type,status,reference,idempotency_key) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) RETURNING reference,status,fee,amount`,[req.ctx!.id,String(req.body?.recipient||''),amount,currency,fee,dest,dest==='INTERNAL'?'COMPLETED':'PENDING',reference,idem]);await c.query(`INSERT INTO bashpay_transactions(user_id,type,status,amount,currency,description) VALUES($1,'TRANSFER',$2,$3,$4,$5)`,[req.ctx!.id,dest==='INTERNAL'?'COMPLETED':'PENDING',amount,currency,dest==='INTERNAL'?'BashPay internal transfer':'External payout']);if(fee)await c.query(`INSERT INTO bashpay_treasury(asset_id,balance,available_balance) SELECT id,$1,$1 FROM bashpay_assets WHERE code=$2 ON CONFLICT(asset_id) DO UPDATE SET balance=bashpay_treasury.balance+EXCLUDED.balance,available_balance=bashpay_treasury.available_balance+EXCLUDED.available_balance`,[fee,currency]);return r.rows[0]});if(dest==='EXTERNAL'){try{const p=await provider.transfer({account_bank:String(req.body?.bankCode),account_number:String(req.body?.accountNumber),amount,currency,reference,narration:'BashPay transfer'});await q(`UPDATE bashpay_transfers SET provider_transfer_id=$1,status='SUBMITTED' WHERE reference=$2`,[String(p.id||p.reference||''),reference])}catch(e){await q(`UPDATE bashpay_transfers SET status='FAILED' WHERE reference=$1`,[reference]);throw e}}res.json({...out,executed:false})});
const adminTokens=new Map<string,{clerkId:string;expires:number}>();const adminAttempts=new Map<string,{count:number;resetAt:number}>();const ADMIN_TOKEN_TTL=15*60*1000;
function secureEqual(a:string,b:string){const x=Buffer.from(a),y=Buffer.from(b);return x.length===y.length&&crypto.timingSafeEqual(x,y)}
function deriveAdminSecret(value:string,salt:Buffer){return new Promise<Buffer>((resolve,reject)=>crypto.scrypt(value,salt,32,{N:16384,r:8,p:1},(err,key)=>err?reject(err):resolve(key as Buffer)))}
async function hashAdminSecret(value:string){const salt=crypto.randomBytes(16);const hash=await deriveAdminSecret(value,salt);return`${salt.toString('hex')}:${hash.toString('hex')}`}
async function verifyAdminSecret(value:string,stored:string){const[sh,hh]=stored.split(':');if(!sh||!hh)return false;try{const derived=await deriveAdminSecret(value,Buffer.from(sh,'hex')),expected=Buffer.from(hh,'hex');return expected.length===derived.length&&crypto.timingSafeEqual(expected,derived)}catch{return false}}
async function adminSecurity(){const rows=await q<{id:number;code4_hash:string;code14_hash:string;master8_hash:string}>(`SELECT id,code4_hash,code14_hash,master8_hash FROM bashpay_admin_security WHERE id=1 LIMIT 1`);if(rows[0])return rows[0];const code4=String(process.env.ADMIN_UNLOCK_CODE_4||''),code14=String(process.env.ADMIN_UNLOCK_CODE_14||''),master8=String(process.env.ADMIN_MASTER_PIN_8||'');if(!/^\\d{4}$/.test(code4)||!/^\\d{14}$/.test(code14)||!/^\\d{8}$/.test(master8))throw Error('BashPay admin security is not configured. Set the 4-digit, 14-digit, and 8-digit owner secrets in Railway.');const row=(await q<{id:number;code4_hash:string;code14_hash:string;master8_hash:string}>(`INSERT INTO bashpay_admin_security(id,code4_hash,code14_hash,master8_hash) VALUES(1,$1,$2,$3) RETURNING id,code4_hash,code14_hash,master8_hash`,[await hashAdminSecret(code4),await hashAdminSecret(code14),await hashAdminSecret(master8)]))[0];return row}
async function validAdminToken(req:any){const token=String(req.get('X-Admin-Token')||''),entry=adminTokens.get(token);if(!entry)return false;if(entry.expires<Date.now()){adminTokens.delete(token);return false}return Boolean(req.ctx?.clerkId&&entry.clerkId===req.ctx.clerkId)}
app.post('/api/admin/unlock',protect,async(req,res)=>{const key=req.ctx!.clerkId;const now=Date.now();const attempt=adminAttempts.get(key);if(attempt&&attempt.resetAt>now&&attempt.count>=5)return res.status(429).json({error:'Too many admin unlock attempts. Try again later.'});let security:any;try{security=await adminSecurity()}catch(e){return res.status(503).json({error:e instanceof Error?e.message:'Admin security is not configured.'})}const code4=String(req.body?.code4||''),code14=String(req.body?.code14||'');if(!/^\\d{4}$/.test(code4)||!/^\\d{14}$/.test(code14))return res.status(400).json({error:'Invalid owner key format.'});const ok=await verifyAdminSecret(code4,security.code4_hash)&&await verifyAdminSecret(code14,security.code14_hash);if(!ok){const next=attempt&&attempt.resetAt>now?{count:attempt.count+1,resetAt:attempt.resetAt}:{count:1,resetAt:now+15*60*1000};adminAttempts.set(key,next);return res.status(403).json({error:'Owner security verification failed.'})}adminAttempts.delete(key);const token=crypto.randomBytes(32).toString('hex');adminTokens.set(token,{clerkId:key,expires:now+ADMIN_TOKEN_TTL});await q(`INSERT INTO bashpay_audit_log(actor_clerk_user_id,action,resource_type,metadata) VALUES($1,'ADMIN_UNLOCK','admin',\$2)`,[key,JSON.stringify({expiresInSeconds:ADMIN_TOKEN_TTL/1000})]);return res.json({ok:true,token,expiresInSeconds:ADMIN_TOKEN_TTL/1000})});
app.post('/api/admin/security/rotate',protect,async(req,res)=>{if(!await validAdminToken(req))return res.status(403).json({error:'Admin unlock required'});const masterPin=String(req.body?.masterPin||''),new4=String(req.body?.newCode4||''),new14=String(req.body?.newCode14||'');if(!/^\\d{8}$/.test(masterPin))return res.status(400).json({error:'The security management PIN must be exactly 8 digits.'});if(!/^\\d{4}$/.test(new4))return res.status(400).json({error:'The new 4-digit owner key must be exactly 4 digits.'});if(!/^\\d{14}$/.test(new14))return res.status(400).json({error:'The new 14-digit owner key must be exactly 14 digits.'});const security=await adminSecurity();if(!await verifyAdminSecret(masterPin,security.master8_hash))return res.status(403).json({error:'Security management PIN is incorrect.'});await q(`UPDATE bashpay_admin_security SET code4_hash=$1,code14_hash=$2,updated_at=NOW() WHERE id=1`,[await hashAdminSecret(new4),await hashAdminSecret(new14)]);await q(`INSERT INTO bashpay_audit_log(actor_clerk_user_id,action,resource_type,metadata) VALUES($1,'ADMIN_LOCKS_ROTATED','admin',\$2)`,[req.ctx!.clerkId,JSON.stringify({codeLengths:[4,14]})]);return res.json({ok:true,message:'Owner locks rotated successfully.'})});
app.post('/api/admin/lock',protect,async(req,res)=>{const token=String(req.get('X-Admin-Token')||'');const valid=await validAdminToken(req);if(valid)adminTokens.delete(token);return res.json({ok:true})});
app.post('/api/exchange-preview',protect,async(req,res)=>{const amount=Number(req.body?.amount),from=String(req.body?.from||'').toUpperCase(),to=String(req.body?.to||'').toUpperCase();if(from===to)return res.json({from,to,amount,rate:1,result:amount,source:'same-currency',executed:false});const r=await q(`SELECT rate,source FROM bashpay_exchange_rates WHERE from_code=$1 AND to_code=$2 LIMIT 1`,[from,to]);if(!r[0])return res.json({from,to,amount,rate:null,result:null,source:'unavailable',executed:false});res.json({from,to,amount,rate:Number(r[0].rate),result:amount*Number(r[0].rate),source:r[0].source||'BashPay',executed:false})});
app.get('/api/admin/status',protect,async(req,res)=>res.json({allowed:validAdminToken(req)}));
app.get('/api/admin/treasury',protect,async(req,res)=>{if(!validAdminToken(req))return res.status(403).json({error:'Admin unlock required'});res.json({treasury:await q(`SELECT t.*,a.code asset_code FROM bashpay_treasury t JOIN bashpay_assets a ON a.id=t.asset_id ORDER BY a.code`)})});
app.get('/api/admin/audit',protect,async(req,res)=>{if(!validAdminToken(req))return res.status(403).json({error:'Admin unlock required'});res.json({events:await q(`SELECT * FROM bashpay_audit_log ORDER BY created_at DESC LIMIT 100`)})});
const dir=path.dirname(fileURLToPath(import.meta.url));const clientRoot=path.resolve(dir,'../client');app.use(express.static(clientRoot));app.use((req,res,next)=>{if(req.method==='GET')return res.sendFile(path.resolve(clientRoot,'index.html'));next()});app.use((e:any,_req:any,res:any,_next:any)=>{console.error(e);res.status(500).json({error:process.env.NODE_ENV==='production'?'Internal server error':e?.message||'Error'})});
migrate().then(()=>adminSecurity()).then(()=>app.listen(port,()=>console.log(`BashPay on ${port}`))).catch(e=>{console.error(e);process.exit(1)});
