import crypto from'node:crypto';

const v3Base=()=>process.env.FLW_ENV==='production'?'https://api.flutterwave.com':'https://developersandbox-api.flutterwave.com';
const v4Base=()=>process.env.FLW_ENV==='production'?'https://api.flutterwave.com':'https://developersandbox-api.flutterwave.com';
const secretKey=()=>{const k=process.env.FLW_SECRET_KEY?.trim();if(!k)throw Error('Flutterwave server API key is not configured');return k};
let tokenCache:{token:string;expiresAt:number}|null=null;

async function v4Token(){const id=process.env.FLW_CLIENT_ID?.trim(),secret=process.env.FLW_CLIENT_SECRET?.trim();if(!id||!secret)throw Error('Flutterwave v4 client credentials are not configured');if(tokenCache&&tokenCache.expiresAt>Date.now()+30000)return tokenCache.token;const body=new URLSearchParams({client_id:id,client_secret:secret,grant_type:'client_credentials'});const r=await fetch('https://idp.flutterwave.com/realms/flutterwave/protocol/openid-connect/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body});const b=await r.json().catch(()=>({}));if(!r.ok||!b.access_token)throw Error(b.error_description||b.message||'Flutterwave OAuth authentication failed');tokenCache={token:String(b.access_token),expiresAt:Date.now()+Math.max(60,Number(b.expires_in||600))*1000};return tokenCache.token}

async function flwV3(path:string,init:RequestInit={}){const h=new Headers(init.headers);h.set('Authorization',`Bearer ${secretKey()}`);h.set('Content-Type','application/json');const r=await fetch(v3Base()+path,{...init,headers:h});const b=await r.json().catch(()=>({}));if(!r.ok||b.status==='error')throw Error(b.message||b.error?.message||`Flutterwave error ${r.status}`);return b.data??b}
async function flwV4(path:string,init:RequestInit={}){const h=new Headers(init.headers);h.set('Authorization',`Bearer ${await v4Token()}`);h.set('Content-Type','application/json');if(!h.has('X-Trace-Id'))h.set('X-Trace-Id',crypto.randomUUID());if(init.method&&init.method.toUpperCase()==='POST'&&!h.has('X-Idempotency-Key'))h.set('X-Idempotency-Key',crypto.randomUUID());const r=await fetch(v4Base()+path,{...init,headers:h});const b=await r.json().catch(()=>({}));if(!r.ok||b.status==='failed'||b.status==='error')throw Error(b.message||b.error?.message||`Flutterwave v4 error ${r.status}`);return b.data??b}

export const providerStatus=()=>({configured:Boolean(process.env.FLW_SECRET_KEY),v4Configured:Boolean(process.env.FLW_CLIENT_ID&&process.env.FLW_CLIENT_SECRET),environment:process.env.FLW_ENV==='production'?'production':'sandbox',livePaymentsEnabled:process.env.LIVE_PAYMENTS_ENABLED==='true'});

export async function checkout(x:{tx_ref:string;amount:number;currency:string;email:string;redirect_url:string}){return flwV3('/v3/payments',{method:'POST',body:JSON.stringify({tx_ref:x.tx_ref,amount:x.amount,currency:x.currency,redirect_url:x.redirect_url,payment_options:'card,banktransfer,ussd,account,opay',customer:{email:x.email},customizations:{title:'BashPay',description:'Fund your BashPay wallet'},configuration:{session_duration:15,max_retry_attempt:5}})})}

export async function banks(country='NG'){return flwV4(`/banks?country=${encodeURIComponent(country)}`)}
export async function resolve(bankCode:string,accountNumber:string,currency='NGN'){return flwV4('/banks/account-resolve',{method:'POST',body:JSON.stringify({account:{code:bankCode,number:accountNumber},currency})})}
export async function transfer(x:{account_bank:string;account_number:string;amount:number;currency:string;reference:string;narration:string;beneficiary_name?:string;callback_url?:string}){return flwV4('/direct-transfers',{method:'POST',body:JSON.stringify({action:'instant',type:'bank',callback_url:x.callback_url,narration:x.narration,reference:x.reference,payment_instruction:{amount:{value:x.amount,applies_to:'destination_currency'},source_currency:x.currency,destination_currency:x.currency,recipient:{bank:{code:x.account_bank,account_number:x.account_number},name:{first:(x.beneficiary_name||'BashPay Recipient').split(' ')[0]||'BashPay',last:(x.beneficiary_name||'Recipient').split(' ').slice(1).join(' ')||'Recipient'},email:''}}})})}
export async function verifyTransfer(id:string){return flwV4(`/transfers/${encodeURIComponent(id)}`)}
export async function verifyCharge(id:string){return flwV4(`/charges/${encodeURIComponent(id)}`)}
export async function verify(id:string|number){return flwV3(`/v3/transactions/${encodeURIComponent(String(id))}/verify`)}
